# Generated by Django 4.2.10 on 2025-06-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_is_available'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_add_initial_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='room_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Assign a group to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('housekeeping', 'Housekeeping'), ('receptionist', 'Receptionist'), ('maintenance', 'Maintenance'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
