# Generated by Django 4.2.10 on 2025-06-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_alter_user_options_remove_studentprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='application_status',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Assign a group to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_users', to='auth.group', verbose_name='Role'),
        ),
    ]
