# Generated by Django 4.2.10 on 2025-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
