# Generated by Django 4.2.10 on 2025-06-06 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelcertificate',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='hostelcertificate',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='hostelcertificate',
            name='download_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='hostelcertificate',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hostelcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
    ]
