# Generated by Django 4.2.10 on 2025-06-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
