# Generated by Django 4.2.10 on 2025-06-14 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0006_alter_maintenancerequest_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancestaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
