# Generated by Django 4.2.10 on 2025-06-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenancestaff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_create',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancestaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='maintenance.maintenancerequest'),
        ),
    ]
