# Generated by Django 4.2.10 on 2025-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenancerequest_request_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_create',
            field=models.BooleanField(default=False),
        ),
    ]
