# Generated by Django 4.2.10 on 2025-06-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0009_alter_maintenancerequest_request_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
