# Generated by Django 4.2.10 on 2025-06-06 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_enrollment_date_and_more'),
        ('bookings', '0002_hostelcertificate_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelcertificate',
            name='booking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
        migrations.DeleteModel(
            name='BookingCancellation',
        ),
        migrations.DeleteModel(
            name='HostelCertificate',
        ),
    ]
