# Generated by Django 4.2.10 on 2025-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('occupancy', 'Occupancy Report'), ('payments', 'Payments Report'), ('maintenance', 'Maintenance Report')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
