# Generated by Django 4.2.10 on 2025-06-14 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
